mutation($engines: [SearchEngineInput]) {
  search {
    updateSearchEngines(engines: $engines) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
